<div id="admin">
	<h2>Facility Editing</h2>
	<p>This is the place that you are going to set all of the options for the Reserve system. Select one of the options from the right. If you get in trouble <a href="mailto:webmaster@ccmr.cornell.edu" title="webmaster@ccmr.cornell.edu">give me a shout</a>.</p>
	<h3>Facility Configuration</h3>
	<p>Gives you access to change:</p>
	<ul>
		<li>Opening and Closing hours of your facility</li>
		<li>Time grid resolution</li>
		<li>Define the window which you can view reservations</li>
		<li>Define the window a user can edit a reservation</li>
	</ul>
	<h3>Facility Description</h3>
	<p>Edit information about your facility, including:</p>
	<ul>
		<li>Full and Short Name of the Facility</li>
		<li>Full and Breif Description</li>
		<li>Location of the Facility</li>
		<li>General facility Contact Information</li>
		<li>Rules for the facility</li>
		<li>Faculty Advisor</li>
		<li>Set whether the facility is to be scheduled at all</li>
	</ul>
	<h3>Instrument List</h3>
	<p>Edit/ add/ remove instruments in your facility, as well as editing instrument:</p>
	<ul>
		<li>Full and Abbreviated Name</li>
		<li>Full and Brief Description</li>
		<li>Location</li>
		<li>Whether or not to schedule it in this Reserve system</li>
		<li>The order in which it is displayed in the Day view</li>
		<li>AND - Defining users who are approved for reserving instrument</li>
	</ul>
</div>